var meuNome = 'Lana'
var minhaidade = '20.9'
var minhaaltura = 1.69
var estavivo = false
console.log(`Olá Mundo, Meu nome é ${meuNome},tenho ${minhaidade} e ${minhaaltura}m de altura`)
console.log(typeof (estavivo))
console.log(`parabens voce completou ${parseInt(minhaidade) + 1}`)





const n1 = 100
const n2 = 3
const total = n1 * n2

console.log(total)


const celsius = 53
const fahrenheit = ((celsius / 100)) * 180 + 32
const kelvin =

    //serve para imprimir os valores 
    console.log(${ celsius })°cé equivalente a ${ kelvin } °k)
if (celsius >= 40) {
    console.log("o tempo esta muito quente")
}


else if (celsius >= 26 && celsius < 40) {
    console.log("o tempo está quente")
}
else if ("o tempo esá frio")



    //evento entrada
    var nome = "kelvin";
var idade = 17;
var acompanhante =false;


if (idade >= 18){
    console.log(`maior de idade,seja bem vindo`${nome})
}
else if (idade < 18 && acompanhante == true) {
 console.log(`menor de idade,bem-vindo${nome}` )
 }else {
console.log(`${nome} voce não pode entrar`)
 }

 

